#!/usr/bin/env python3

import sys
from pathlib import Path
from xpander.fs import Settings, Manager
from xpander.control import BaseClient, ClientType, MSG, MsgType
from xpander.gtk_gui import Editor


NAME = 'xpander-gui'
if getattr(sys, 'frozen', False):
	__file__ = sys.executable


class EditorClient(BaseClient):

	def __init__(self, name, client):

		try:
			super().__init__(name, client)
			self.offline = False
		except ConnectionRefusedError:
			self.client = client
			self.stop = True
			self.offline = True
		self.editor = None

	def process_msg(self, msg):

		if self.editor:
			self.editor.process_msg(msg)
		else:
			super().process_msg(msg)


settings = Settings()
client = EditorClient(NAME, (ClientType.EDITOR, NAME))
daemon_path = Path(__file__).resolve().parent
editor = Editor(
	settings, Manager(settings, daemon_path), client, daemon_path)
client.editor = editor
client.start()
editor.start()
